# -*- coding: utf-8 -*-
"""password_generator.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQDGufIj676hteu_m6pLatKv6FLt3ePG
"""

import random
from string import digits
from string import punctuation
from string import ascii_letters


simbolos = ascii_letters + digits + punctuation
seguranca = random.SystemRandom()
senha = "".join(seguranca.choice(simbolos) for i in range(20))

print(senha)