# -*- coding: utf-8 -*-
"""simple_translater.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQDGufIj676hteu_m6pLatKv6FLt3ePG
"""

# pip install translate

from translate import Translator


lang = Translator(from_lang="English", to_lang ="Portuguese")
result = lang.translate("Hello Guys")

print(result)